# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-03 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProveedorSemen', '0001_initial'),
        ('Raza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemenToro',
            fields=[
                ('id_semen_toro', models.AutoField(primary_key=True, serialize=False)),
                ('edad', models.IntegerField()),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_semen_proveedor', to='ProveedorSemen.ProveedorSemen')),
                ('id_raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_semen_raza', to='Raza.Raza')),
            ],
            options={
                'ordering': ('id_semen_toro',),
            },
        ),
    ]
