# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-03 00:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bovino', '0004_auto_20161003_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medidas',
            fields=[
                ('id_medida', models.AutoField(primary_key=True, serialize=False)),
                ('peso', models.DecimalField(decimal_places=2, default=None, max_digits=4)),
                ('alzada', models.DecimalField(decimal_places=2, default=None, max_digits=4)),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('id_bovino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_medida_bovino', to='Bovino.Bovino')),
            ],
        ),
    ]
