# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-03 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Granja', '0001_initial'),
        ('EstadoEspacio', '0001_initial'),
        ('TipoEspacio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id_espacio', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacidad', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('aforo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje_desperdicio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_estado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_espacio_estado', to='EstadoEspacio.EstadoEspacio')),
                ('id_granja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_espacio_granja', to='Granja.Granja')),
                ('id_tipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_espacio_tipo', to='TipoEspacio.TipoEspacio')),
            ],
            options={
                'ordering': ('id_espacio',),
            },
        ),
    ]
