# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-02 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Raza', '0001_initial'),
        ('Bovino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bovino',
            name='id_raza',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Raza.Raza'),
        ),
    ]
