# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-02 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TipoParto', '0001_initial'),
        ('Sexo', '0001_initial'),
        ('EstadoBovino', '0001_initial'),
        ('Procedencia', '0001_initial'),
        ('Etapa', '0001_initial'),
        ('Granja', '0001_initial'),
        ('Bovino', '0002_bovino_id_raza'),
    ]

    operations = [
        migrations.AddField(
            model_name='bovino',
            name='edad_primer_parto',
            field=models.IntegerField(default=None, verbose_name='Edad del primer parto'),
        ),
        migrations.AddField(
            model_name='bovino',
            name='fechaEntrada',
            field=models.DateTimeField(default=None, verbose_name='Fecha de entrada'),
        ),
        migrations.AddField(
            model_name='bovino',
            name='fechaSalida',
            field=models.DateTimeField(default=None, verbose_name='Fecha de salida'),
        ),
        migrations.AddField(
            model_name='bovino',
            name='fecha_destete',
            field=models.DateTimeField(default=None, verbose_name='Fecha de destete'),
        ),
        migrations.AddField(
            model_name='bovino',
            name='fecha_nacimiento',
            field=models.DateTimeField(default=None, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='bovino',
            name='fecha_primer_servicio',
            field=models.DateTimeField(default=None, verbose_name='Fecha de primer servicio'),
        ),
        migrations.AddField(
            model_name='bovino',
            name='id_estado',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='EstadoBovino.EstadoBovino'),
        ),
        migrations.AddField(
            model_name='bovino',
            name='id_etapa',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Etapa.Etapa'),
        ),
        migrations.AddField(
            model_name='bovino',
            name='id_granja',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Granja.Granja'),
        ),
        migrations.AddField(
            model_name='bovino',
            name='id_madre',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='id_madre_bovino', to='Bovino.Bovino'),
        ),
        migrations.AddField(
            model_name='bovino',
            name='id_padre',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='id_padre_bovino', to='Bovino.Bovino'),
        ),
        migrations.AddField(
            model_name='bovino',
            name='id_parto',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='TipoParto.TipoParto'),
        ),
        migrations.AddField(
            model_name='bovino',
            name='id_procedencia',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Procedencia.Procedencia'),
        ),
        migrations.AddField(
            model_name='bovino',
            name='id_sexo',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Sexo.Sexo'),
        ),
        migrations.AddField(
            model_name='bovino',
            name='motivo_salida',
            field=models.TextField(default=None, max_length=140),
        ),
        migrations.AddField(
            model_name='bovino',
            name='nombre',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='bovino',
            name='peso_nacimiento',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
    ]
