# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-03 00:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bovino', '0003_auto_20161002_2325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bovino',
            options={'ordering': ('id_bovino',)},
        ),
    ]
