# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-03 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactorialAjustado',
            fields=[
                ('id_factorial', models.AutoField(primary_key=True, serialize=False)),
                ('dias', models.IntegerField()),
                ('factor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ('id_factorial',),
            },
        ),
    ]
