# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-03 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorSemen',
            fields=[
                ('nit', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('nit',),
            },
        ),
    ]
