# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-03 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Espacio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MantenimientoEspacio',
            fields=[
                ('id_mant_espacio', models.AutoField(primary_key=True, serialize=False)),
                ('diasDescanso', models.IntegerField()),
                ('cantPorquinaza', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantBovinaza', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantUrea', models.DecimalField(decimal_places=2, max_digits=10)),
                ('controlPlagas', models.IntegerField()),
                ('cantCalDol', models.DecimalField(decimal_places=2, max_digits=10)),
                ('regarEstiercol', models.IntegerField()),
                ('controlMaleza', models.IntegerField()),
                ('guadana', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('id_espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_mant_espacio', to='Espacio.Espacio')),
            ],
            options={
                'ordering': ('id_mant_espacio',),
            },
        ),
    ]
