"""
Django settings for SistemaGranja project.

Generated by 'django-admin startproject' using Django 1.9.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&jbyu8ftsfq06!se=ua2dpmdyw@aw3&j&8a55ojs((oc-b+-7%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    #'granja.apps.GranjaConfig',
    #'potrero.apps.PotreroConfig',
    'Alimento.apps.AlimentoConfig',
    'Bovino.apps.BovinoConfig',
    'Granja.apps.GranjaConfig',
    'Raza.apps.RazaConfig',
    'Departamento.apps.DepartamentoConfig',
    'Municipio.apps.MunicipioConfig',
    'TipoParto.apps.TipopartoConfig',
    'Procedencia.apps.ProcedenciaConfig',
    'EstadoBovino.apps.EstadobovinoConfig',
    'Etapa.apps.EtapaConfig',
    'Sexo.apps.SexoConfig',
    'ControlMastitis.apps.ControlmastitisConfig',
    'EntregaLeche.apps.EntregalecheConfig',
    'Medidas.apps.MedidasConfig',
    'Espacio.apps.EspacioConfig',
    'EstadoEspacio.apps.EstadoespacioConfig',
    'TipoEspacio.apps.TipoespacioConfig',
    'MantenimientoEspacio.apps.MantenimientoespacioConfig',
    'EstadoPalpacion.apps.EstadopalpacionConfig',
    'EstadoSanidad.apps.EstadosanidadConfig',
    'FactorialAjustado.apps.FactorialajustadoConfig',
    'Medicamento.apps.MedicamentoConfig',
    'EstadoGranja.apps.EstadogranjaConfig',
    'Sanidad.apps.SanidadConfig',
    'ViaAplicacion.apps.ViaaplicacionConfig',
    'Palpacion.apps.PalpacionConfig',
    'Servicio.apps.ServicioConfig',
    'Reproduccion.apps.ReproduccionConfig',
    'ZonaVida.apps.ZonavidaConfig',
    'ProveedorSemen.apps.ProveedorsemenConfig',
    'SemenToro.apps.SementoroConfig',
    'Usuario.apps.UsuarioConfig',
    'InicioSesion.apps.IniciosesionConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SistemaGranja.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SistemaGranja.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'granjabd',
        'USER': 'granjero',
        'PASSWORD': 'Granjero@123',
        'HOST': 'localhost',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
STATIC_URL = '/static/'
MEDIA_ROOT = 'media'
MEDIA_URL = '/media/'
