# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-03 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bovino', '0005_auto_20161003_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reproduccion',
            fields=[
                ('id_reproduccion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_servicio', models.DateTimeField()),
                ('proximoCelo', models.DateTimeField()),
                ('fechaPosibleParto', models.DateTimeField()),
                ('fechaSecado', models.DateTimeField()),
                ('id_bovino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_reproduccion_bovino', to='Bovino.Bovino')),
                ('id_cria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_reproduccion_cria', to='Bovino.Bovino')),
            ],
            options={
                'ordering': ('id_reproduccion',),
            },
        ),
    ]
