# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-03 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EstadoPalpacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palpacion',
            fields=[
                ('id_palpacion', models.AutoField(primary_key=True, serialize=False)),
                ('observacion', models.CharField(max_length=140)),
                ('fecha', models.DateTimeField()),
                ('id_estado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_palpacion_estado', to='EstadoPalpacion.EstadoPalpacion')),
            ],
            options={
                'ordering': ('id_palpacion',),
            },
        ),
    ]
