# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-03 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Reproduccion', '0001_initial'),
        ('Palpacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='palpacion',
            name='id_reproduccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_palpacion_reproduccion', to='Reproduccion.Reproduccion'),
        ),
    ]
