# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-06 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=16)),
                ('nombre1', models.CharField(max_length=50)),
                ('nombre2', models.CharField(max_length=50)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('usuario',),
            },
        ),
    ]
