# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-03 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EstadoGranja', '0001_initial'),
        ('Granja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='granja',
            name='id_estado',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='id_granja_estado', to='EstadoGranja.EstadoGranja'),
        ),
    ]
